//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public int Consult_No { get; set; }
        public Nullable<decimal> Con_Weight { get; set; }
        public Nullable<decimal> Con_Hist_Height { get; set; }
        public Nullable<decimal> Con_Hist_BMI { get; set; }
        public string Con_Hist_UrineTest { get; set; }
        public Nullable<decimal> Con_Hist_Temperature { get; set; }
        public Nullable<decimal> Con_Hist_HeartRate { get; set; }
        public Nullable<decimal> Con_Hist_Waist { get; set; }
        public string Con_Hist_BloodPressure { get; set; }
        public Nullable<decimal> Con_Hist_BloodGlucose { get; set; }
        public string Con_Hist_Oedema { get; set; }
        public Nullable<decimal> Con_Hist_EpilepsyBloods { get; set; }
        public string Con_Consult_Date { get; set; }
        public string Con_Note { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Patient_No { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
