//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family_Member
    {
        public int Member_ID { get; set; }
        public int Patient_No { get; set; }
        public Nullable<int> Relationship { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual FamilyRelationship FamilyRelationship { get; set; }
    }
}
