//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Daspoort_ClinicEntities2 : DbContext
    {
        public Daspoort_ClinicEntities2()
            : base("name=Daspoort_ClinicEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultation> Consultations { get; set; }
        public virtual DbSet<Family_Member> Family_Member { get; set; }
        public virtual DbSet<FamilyRelationship> FamilyRelationships { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
    }
}
